log:
  disable_sentry: true
  level: "warn"

db:
  url: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"

listener:
  addr: :9100

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: blob-svc
  service_port: 80
